security:
    encoders:
        Prevem\CoreBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_COMPOSE:      [ROLE_USER]
        ROLE_RENDER:       [ROLE_USER]
        ROLE_ADMIN:        [ROLE_COMPOSE, ROLE_RENDER]
        ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #in_memory:
            #memory:
                #users:
                    #restapi:  { password: secretpw, roles: ROLE_USER }
        main:
            entity: { class: Prevem\CoreBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern: ^/
            anonymous:  ~
            stateless:  true
            http_basic:
                #realm: "Demo REST API (username: restapi, password: secretpw)"
            guard:
              authenticator:
                          - jwt_token_authenticator
