services:
#    prevem_core.example:
#        class: Prevem\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    jwt_token_authenticator:
        class:  Prevem\CoreBundle\Security\JwtTokenAuthenticator
        #autowire: true
        arguments: ['@lexik_jwt_authentication.jwt_encoder', '@doctrine.orm.entity_manager']
