services:
#    prevem_core.example:
#        class: Prevem\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    token_authenticator:
        class:  Prevem\CoreBundle\Security\TokenAuthenticator
        arguments: ['@lexik_jwt_authentication.jwt_encoder', '@doctrine.orm.entity_manager', '@service_container']

    prevem_core.prevem_utils:
        class:  Prevem\CoreBundle\Utility
        arguments: ['@lexik_jwt_authentication.jwt_encoder', '@doctrine.orm.entity_manager', '@service_container']

